// src/state/playlist/playlistTypes.js
export const PLAYLIST_MOVE_UP_SONG = 'PLAYLIST_MOVE_UP_SONG';
export const PLAYLIST_MOVE_DOWN_SONG = 'PLAYLIST_MOVE_DOWN_SONG';
export const PLAYLIST_DELETE_FROM_LIST = 'PLAYLIST_DELETE_FROM_LIST';
