// src/state/playlist/playlistTypes.js

//for saga
export const PLAYLIST_MOVE_UP_SONG = 'PLAYLIST_MOVE_UP_SONG';
export const PLAYLIST_MOVE_DOWN_SONG = 'PLAYLIST_MOVE_DOWN_SONG';
export const PLAYLIST_DELETE_FROM_LIST = 'PLAYLIST_DELETE_FROM_LIST';
export const PLAYLIST_GET = "PLAYLIST_GET";
export const PLAYLIST_TRACK_GET = "PLAYLIST_TRACK_GET";



//for reducer
export const PLAYLIST_MOVE_UP_SONG_SUCCESS = 'PLAYLIST_MOVE_UP_SONG_SUCCESS';
export const PLAYLIST_MOVE_UP_SONG_ERROR = 'PLAYLIST_MOVE_UP_SONG_ERROR';
export const PLAYLIST_MOVE_DOWN_SONG_SUCCESS = 'PLAYLIST_MOVE_DOWN_SONG_SUCCESS';
export const PLAYLIST_MOVE_DOWN_SONG_ERROR = 'PLAYLIST_MOVE_DOWN_SONG_ERROR';
export const PLAYLIST_DELETE_FROM_LIST_SUCCESS = 'PLAYLIST_DELETE_FROM_LIST_SUCCESS';
export const PLAYLIST_DELETE_FROM_LIST_ERROR = 'PLAYLIST_DELETE_FROM_LIST_ERROR';
export const PLAYLIST_GET_SUCCESS = "PLAYLIST_GET_SUCCESS";
export const PLAYLIST_GET_ERROR = "PLAYLIST_GET_ERROR";
export const PLAYLIST_TRACK_GET_SUCCESS = "PLAYLIST_TRACK_GET_SUCCESS";
export const PLAYLIST_TRACK_GET_ERROR = "PLAYLIST_TRACK_GET_ERROR";
export const PLAYLIST_TRACK_GET_ALL_DONE = "PLAYLIST_TRACK_GET_ALL_DONE";
export const PLAYLIST_SELECT = "PLAYLIST_SELECT";
export const PLAYLIST_FETCH_PROGRESS = "PLAYLIST_FETCH_PROGRESS";

