// src/state/tracks/tracksTypes.js
//export const PLAYLIST_DELETE_FROM_LIST = 'PLAYLIST_DELETE_FROM_LIST';
export const PLAYLIST_ADD_TO_TRACKS = 'PLAYLIST_ADD_TO_TRACKS';
export const TRACKS_SAVE_LOCATIONS = 'TRACKS_SAVE_LOCATION';
export const TRACKS_DELETE_LOCATIONS = 'TRACKS_DELETE_LOCATIONS';
