// src/state/fbase/fbaseTypes.js
export const FBASE_INIT = 'FBASE_INIT';
export const FBASE_INIT_COMPLETED = 'FBASE_INIT_COMPLETED';
export const FBASE_AUTHENTICATE = 'FBASE_AUTHENTICATE';
export const FBASE_AUTHENTICATE_SUCCESS = 'FBASE_AUTHENTICATE_SUCCESS';
export const FBASE_AUTHENTICATE_ERROR = 'FBASE_AUTHENTICATE_ERROR';
export const FBASE_SET_UID = 'FBASE_SET_UID';
export const FBASE_SIGN_OUT = 'FBASE_SIGN_OUT';
export const FBASE_SIGN_OUT_SUCCESS = 'FBASE_SIGN_OUT_SUCCESS';
export const FBASE_SIGN_OUT_ERROR = 'FBASE_SIGN_OUT_ERROR';